# Generated by Django 5.1.7 on 2025-04-11 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0004_create_user_profiles'),
    ]

    operations = [
    ]
