# Generated by Django 5.1.7 on 2025-04-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0005_auto_20250411_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='answers',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
