# Generated by Django 5.1.7 on 2025-04-13 10:03

from django.db import migrations

# Function to populate avatar URLs
def populate_avatar_urls(apps, schema_editor):
    UserProfile = apps.get_model('quiz_app', 'UserProfile')
    for profile in UserProfile.objects.all():
        if not profile.avatar_url: # Only generate if it doesn't exist
            # Generate avatar URL using DiceBear personas style based on username
            # Make sure the user relationship is loaded to avoid extra queries if needed
            # (though UserProfile is loaded via all(), the user might need select_related in large datasets)
            username = profile.user.username 
            avatar_url = f"https://api.dicebear.com/8.x/personas/svg?seed={username}"
            profile.avatar_url = avatar_url
            profile.save()

# Optional: Function to run if migration is reversed (can be a no-op)
def reverse_populate_avatar_urls(apps, schema_editor):
    # If you wanted to clear the URLs on rollback, you could do:
    # UserProfile = apps.get_model('quiz_app', 'UserProfile')
    # UserProfile.objects.update(avatar_url='') 
    pass # Keep it simple for now


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0007_userprofile_avatar_url'),
    ]

    operations = [
        # Add the RunPython operation
        migrations.RunPython(populate_avatar_urls, reverse_code=reverse_populate_avatar_urls),
    ]
