from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.home, name='home'),
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.custom_logout, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('admindashboard/', views.admin_dashboard, name='admindashboard'),
    path('profile/', views.profile, name='profile'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('ques/', views.ques, name='ques'),
    path('pyquiz/', views.pyquiz, name='pyquiz'),
    path('cppquiz/', views.cppquiz, name='cppquiz'),
    path('submit_quiz/', views.submit_quiz, name='submit_quiz'),
    path('submit_cpp_quiz/', views.submit_cpp_quiz, name='submit_cpp_quiz'),
    path('submit_answer/', views.submit_answer, name='submit_answer'),
    path('contact_us/', views.contact_us, name='contact_us'),
    path('about_us/', views.about_us, name='about_us'),
    path('create_quiz/', views.create_quiz, name='create_quiz'),
    path('staff/dashboard/', views.staff_dashboard, name='staff_dashboard'),
    path('staff/delete-attempt/<int:attempt_id>/', views.delete_attempt, name='delete_attempt'),
    path('staff/create-quiz/', views.create_quiz_staff, name='create_quiz_staff'),
    path('staff/delete-quiz/<int:quiz_id>/', views.delete_quiz, name='delete_quiz'),
    path('staff/review-answers/<int:quiz_id>/', views.review_answers, name='review_answers'),
    path('staff/view-attempt/<int:attempt_id>/', views.view_attempt, name='view_attempt'),
    path('quiz/<int:quiz_id>/', views.take_quiz, name='take_quiz'),
    path('quiz/<int:quiz_id>/submit/', views.submit_quiz, name='submit_quiz'),
    path('quiz/<int:attempt_id>/result/', views.quiz_result, name='quiz_result'),
    path('staff/edit-quiz/<int:quiz_id>/', views.edit_quiz, name='edit_quiz'),
    path('search/', views.search_results, name='search_results'),
    path('staff/mark-message-read/<int:message_id>/', views.mark_message_read, name='mark_message_read'),
    path('quiz-categories/', views.quiz_categories, name='quiz_categories'),
    path('statistics/', views.statistics, name='statistics'),
    path('leaderboard/', views.leaderboard, name='leaderboard'),
    path('help_center/', views.help_center, name='help_center'),
    path('faq/', views.faq, name='faq'),
    path('feedback/', views.feedback, name='feedback'),
    path('report_issue/', views.report_issue, name='report_issue'),
    path('suggest_quiz/', views.suggest_quiz, name='suggest_quiz'),
    path('privacy-policy/', views.privacy_policy, name='privacy_policy'),
    path('terms-of-service/', views.terms_of_service, name='terms_of_service'),
    path('cookie-policy/', views.cookie_policy, name='cookie_policy'),
    path('sitemap/', views.sitemap, name='sitemap'),
    path('subscribe-newsletter/', views.subscribe_newsletter, name='subscribe_newsletter'),
]